### ISSUE TITLE
Path to adding new model types?

### ISSUE THREAD

**Issue by kinchahoy** [Pelochus/ezrknn-llm#14]
Pelochus,

Thank you so much for this repo! I'm getting some of the best performance I've seen out of an SBC thanks to your work stitching all these parts together.

I'm trying to convert some new models (particularly multimodal ones) like Florence and Phi 3.5V and it looks like they arn't supported (yet). 

"rkllm-toolkit version: 1.0.1
Not support Florence2ForConditionalGeneration!
Load model failed!"

or 

"root@85839da9239a:/ezrknn-llm/rkllm-toolkit/examples/huggingface# python3 createphi35.py
rkllm-toolkit version: 1.0.1
Not support Phi3VForCausalLM!
Load model failed!"

Could you give me a few pointers on where to start to add new model types? These arn't super complex or different from Phi-3 so I'm hoping there is a config or two somewhere (or perhaps I just need to update some HF repo to the latest inside the docker) to support them.

**Comment by Pelochus** [comment]
Sorry for the late response. Adding compatibility with new models is sadly on Rockchip's end, so I can't guide
