### ISSUE TITLE
Convert custom model from hugging face

### ISSUE THREAD

**Issue by Kracozebr** [Pelochus/ezrknn-llm#16]
Hello, first of all thanks for useful fork!

I try to convert custom model from HF. The model is finetunned version of llama 3.2 1b.
During convertation got the error:
```
rkllm-toolkit version: 1.0.1
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Error: `rope_scaling` must be a dictionary with with two fields, `type` and `factor`, got {'factor': 32.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}!
Catch exception when loading model!
Load model failed!
```

Tried to convert another model that is fine tuning of Qwen2 0.5b model and got the error:
```
rkllm-toolkit version: 1.0.1
Error: data did not match any variant of untagged enum ModelWrapper at line 757443 column 3!
Catch exception when loading model!
Load model failed!
```
Is there chance to convert this models. Anything I can do?

**Comment by Pelochus** [comment]
You must use newer versions of rknn-llm. This repo is currently a bit outdated (will hopefully update it soon). For now, you can use this:

https://github.com/c0zaut/ez-er-rkllm-toolkit

Which is both updated and better than my Docker image
