### ISSUE TITLE
RK3588 NPU Drivers Version

### ISSUE THREAD

**Issue by lzd19981105** [Pelochus/ezrknn-llm#9]
Do you know how to upgrade the npu drivers to 0.9.6 that rkllm needs?

**Comment by Pelochus** [comment]
Easy way is to change your OS to Ubuntu Rockchip or Armbian:
- https://github.com/Joshua-Riek/ubuntu-rockchip
- https://www.armbian.com/

If you want to update the driver in your current OS there is no easy way, you need to recompile the Linux kernel, haven't managed to do it once so I will not make a guide on it
